
CREATE DATABASE invoice;


CREATE USER invoice_db_manager WITH PASSWORD '123456';


GRANT CONNECT ON DATABASE invoice TO invoice_db_manager;


\c invoice


GRANT CREATE ON SCHEMA public TO invoice_db_manager;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO invoice_db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO invoice_db_manager;
